#!/bin/sh

# set root pointer
xsetroot -cursor_name left_ptr

# key bindings
sxhkd &

# panel
#tint2 &

need_dual_monitor = 0

if [[ $need_dual_monitor -eq 0 ]]; then
	/home/terryfung/.screenlayout/home.sh 
	bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
	bspc monitor HDMI1 -d I II III IV V VI VII VIII IX X
	nitrogen --random --set-scaled /home/terryfung/.wallpapers
else
	/home/terryfung/.config/bspwm/my_monitor
	bspc monitor HDMI3 -d 1 2 3 4 5 6 7
	bspc monitor eDP1 -d  8 9 10
	nitrogen --random --set-scaled --head=0 /home/terryfung/.wallpapers
	nitrogen --random --set-scaled --head=1 /home/terryfung/.wallpapers
fi

bspc config window_gap 12
bspc config border_width 1

bspc config split_ratio 0.62
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#test
bspc config click_to_focus true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
#bspc config merge_overlapping_monitors true

# wallpaper
#exec feh --bg-scale /home/terryfung/.wallpapers/forest-outline.png

# polybar
/home/terryfung/.config/polybar/launch.sh &
